import { Student, Certificate, CategoryProgress } from './types';

export const initialStudent: Student = {
  ra: "801234",
  name: "Lucas Ferreira Silva",
  initials: "LF",
  course: "Bacharelado em Ciência da Computação",
  campus: "Câmpus Sorocaba",
  pedagogicalProject: "Projeto Pedagógico 2021",
  status: "Matrícula Regular",
  requiredHours: 210,
  approvedHours: 87,
  pendingHours: 45,
};

export const initialCategoryRules: CategoryProgress[] = [
  {
    category: 'Ensino',
    displayName: 'Ensino (Cursos, Palestras)',
    currentHours: 40,
    maxHours: 60,
    color: '#3b82f6', // blue
    description: 'Cursos de aperfeiçoamento, palestras, seminários, minicursos técnicos com certificado nominal.',
  },
  {
    category: 'Extensão',
    displayName: 'Extensão (Projetos, Organização de Eventos)',
    currentHours: 20,
    maxHours: 40,
    color: '#10b981', // emerald
    description: 'Projetos de extensão comunitária, organização de eventos científicos (SECOMP), hackathons e feiras.',
  },
  {
    category: 'Pesquisa',
    displayName: 'Pesquisa (Iniciação Científica, Publicações)',
    currentHours: 15,
    maxHours: 40,
    color: '#8b5cf6', // purple
    description: 'Iniciação Científica PIBIC/FAPESP, publicação de artigos e apresentação de pôsteres científicos.',
  },
  {
    category: 'Gestão & Representação',
    displayName: 'Gestão & Representação Estudantil',
    currentHours: 12,
    maxHours: 20,
    color: '#f59e0b', // amber
    description: 'Representação de turma, membros de Colegiado de Curso, Diretório Acadêmico e Empresa Júnior.',
  },
  {
    category: 'Cultura, Esporte & Integração',
    displayName: 'Cultura, Esporte & Integração',
    currentHours: 0,
    maxHours: 50,
    color: '#ef4444', // red
    description: 'Atividades culturais, torneios esportivos universitários, oficinas de línguas e integração acadêmica.',
  },
];

export const initialCertificates: Certificate[] = [
  // Lucas Ferreira Silva (Aluno Principal)
  {
    id: "cert-01",
    studentRa: "801234",
    studentName: "Lucas Ferreira Silva",
    title: "Curso de Extensão: Desenvolvimento Web Moderno com React & Redux",
    category: "Ensino",
    issuer: "Coursera / SENAI Nacional",
    submissionDate: "14/03/2023",
    completionDate: "14/03/2023",
    hours: 40,
    status: "PENDENTE",
    hash: "8f9e2a3b1c4e7f90c41b",
    description: "Treinamento intensivo de frontend avançado com React 18, Redux Toolkit e TypeScript com avaliação prática.",
    fileName: "comprovante_react_redux_coursera.pdf",
    fileSize: "1.4 MB",
  },
  {
    id: "cert-02",
    studentRa: "801234",
    studentName: "Lucas Ferreira Silva",
    title: "Organização de Evento: IX Semana Acadêmica da Computação (SECOMP)",
    category: "Extensão",
    issuer: "Departamento de Computação — UFSCar",
    submissionDate: "10/10/2023",
    completionDate: "14/10/2023",
    hours: 20,
    status: "PENDENTE",
    hash: "e3f51a7d8c9012b4e229",
    description: "Comissão organizadora da SECOMP 2023 - Apoio na infraestrutura de laboratórios e recepção de palestrantes.",
    fileName: "declaracao_organizacao_secomp_2023.pdf",
    fileSize: "850 KB",
  },
  {
    id: "cert-03",
    studentRa: "801234",
    studentName: "Lucas Ferreira Silva",
    title: "Apresentação de Trabalho: Computação de Alto Desempenho aplicada à Genômica",
    category: "Pesquisa",
    issuer: "Congresso de Iniciação Científica (CIC UFSCar)",
    submissionDate: "28/11/2023",
    completionDate: "28/11/2023",
    hours: 15,
    status: "PENDENTE",
    hash: "2bc77e9140a158d2f9d2",
    description: "Apresentação oral no 30º CIC UFSCar sobre processamento paralelo em clusters para análise de sequenciamento genético.",
    fileName: "certificado_cic_ufscar_apresentacao.pdf",
    fileSize: "2.1 MB",
  },
  {
    id: "cert-04",
    studentRa: "801234",
    studentName: "Lucas Ferreira Silva",
    title: "Fundamentos de Redes de Computadores",
    category: "Ensino",
    issuer: "SENAI Nacional",
    submissionDate: "10/02/2023",
    completionDate: "05/02/2023",
    hours: 30,
    status: "APROVADO",
    hash: "54a1bb674e1123fa9081",
    feedback: "Homologado pela Comissão Docente. Certificado verificado com sucesso junto ao portal SENAI.",
    fileName: "redes_senai_homologado.pdf",
    fileSize: "920 KB",
  },
  {
    id: "cert-05",
    studentRa: "801234",
    studentName: "Lucas Ferreira Silva",
    title: "Hackathon USP - Programação Avançada",
    category: "Extensão",
    issuer: "USP Câmpus Capital",
    submissionDate: "15/01/2023",
    completionDate: "15/01/2023",
    hours: 20,
    status: "INDEFERIDO",
    hash: "d90184efa71bc549e312",
    feedback: "Certificado sem assinatura institucional válida nem código de validação legível. Favor reenviar com autenticação digital.",
    fileName: "hackathon_usp_invalido.pdf",
    fileSize: "1.1 MB",
  },
  {
    id: "cert-06",
    studentRa: "801234",
    studentName: "Lucas Ferreira Silva",
    title: "Curso Inglês Técnico para TI",
    category: "Ensino",
    issuer: "Fundação Bradesco",
    submissionDate: "Rascunho",
    hours: 12,
    status: "RASCUNHO",
    hash: "rascunho_temp_9120",
    description: "Aguardando envio do certificado final emitido pela plataforma.",
    fileName: "rascunho_comprovante.pdf",
    fileSize: "450 KB",
  },
  {
    id: "cert-07",
    studentRa: "801234",
    studentName: "Lucas Ferreira Silva",
    title: "Atuação no Colegiado do Curso de Computação",
    category: "Gestão & Representação",
    issuer: "DCo - Departamento de Computação UFSCar",
    submissionDate: "20/12/2023",
    hours: 12,
    status: "APROVADO",
    hash: "61fe8910acb7829143a1",
    feedback: "Ata de posse e participação regular conferida pela Secretaria Acadêmica.",
    fileName: "portaria_colegiado_2023.pdf",
    fileSize: "670 KB",
  },

  // Mateus Andrade Santos
  {
    id: "cert-mat-01",
    studentRa: "812932",
    studentName: "Mateus Andrade Santos",
    title: "Organização do Simpósio de IA Sorocaba",
    category: "Extensão",
    issuer: "Comitê de Inteligência Artificial UFSCar",
    submissionDate: "15/05/2025",
    completionDate: "10/05/2025",
    hours: 30,
    status: "PENDENTE",
    hash: "3a91bf88d20e741c9a01",
    description: "Coordenação de mesas redondas e gestão dos trabalhos acadêmicos no Simpósio Regional de IA.",
    fileName: "declaracao_simposio_ia_sorocaba.pdf",
    fileSize: "1.8 MB",
  },

  // Beatriz Souza Lima
  {
    id: "cert-bea-01",
    studentRa: "799042",
    studentName: "Beatriz Souza Lima",
    title: "Iniciação Científica - FAPESP 2024",
    category: "Pesquisa",
    issuer: "FAPESP / DCo UFSCar",
    submissionDate: "14/05/2025",
    completionDate: "30/04/2025",
    hours: 40,
    status: "PENDENTE",
    hash: "7f44a9018e6cd328bf14",
    description: "Relatório final aprovado de IC com bolsa FAPESP em Otimização Combinatória e Grafos.",
    fileName: "relatorio_fapesp_homologado.pdf",
    fileSize: "3.4 MB",
  },

  // Thiago Cardoso Dias
  {
    id: "cert-thi-01",
    studentRa: "801129",
    studentName: "Thiago Cardoso Dias",
    title: "Palestra Tecnológica - IBM Cloud Security",
    category: "Ensino",
    issuer: "IBM Brasil",
    submissionDate: "13/05/2025",
    completionDate: "12/05/2025",
    hours: 4,
    status: "PENDENTE",
    hash: "90da1f54c29188e7321a",
    description: "Palestra de segurança e arquiteturas zero-trust em nuvem híbrida.",
    fileName: "certificado_ibm_cloud_security.pdf",
    fileSize: "780 KB",
  },

  // Aline Oliveira Costa
  {
    id: "cert-ali-01",
    studentRa: "812001",
    studentName: "Aline Oliveira Costa",
    title: "Curso Programação Funcional em Haskell",
    category: "Ensino",
    issuer: "Universidade de São Paulo (USP)",
    submissionDate: "12/05/2025",
    completionDate: "08/05/2025",
    hours: 20,
    status: "PENDENTE",
    hash: "45ec198bb03a27419ef0",
    description: "Curso de extensão universitária em paradigmas funcionais avançados, mônadas e teoria de categorias.",
    fileName: "certificado_haskell_usp.pdf",
    fileSize: "1.2 MB",
  },

  // Rodrigo Cunha Souza
  {
    id: "cert-rod-01",
    studentRa: "800311",
    studentName: "Rodrigo Cunha Souza",
    title: "Atuação como Representante de Turma",
    category: "Gestão & Representação",
    issuer: "Coordenação de Ciência da Computação UFSCar",
    submissionDate: "11/05/2025",
    completionDate: "10/05/2025",
    hours: 10,
    status: "PENDENTE",
    hash: "82bc0914de5520a7b419",
    description: "Representante discente titular junto ao colegiado do curso durante o ano letivo de 2024.",
    fileName: "ata_eleicao_representacao_2024.pdf",
    fileSize: "950 KB",
  },
];

export const triageStudents: Student[] = [
  {
    ra: "801234",
    name: "Lucas Ferreira Silva",
    initials: "LF",
    course: "Bacharelado em Ciência da Computação",
    campus: "Câmpus Sorocaba",
    pedagogicalProject: "Projeto Pedagógico 2021",
    status: "Matrícula Regular",
    requiredHours: 210,
    approvedHours: 135,
    pendingHours: 75,
  },
  {
    ra: "812932",
    name: "Mateus Andrade Santos",
    initials: "MA",
    course: "Bacharelado em Ciência da Computação",
    campus: "Câmpus Sorocaba",
    pedagogicalProject: "Projeto Pedagógico 2021",
    status: "Matrícula Regular",
    requiredHours: 210,
    approvedHours: 95,
    pendingHours: 30,
  },
  {
    ra: "799042",
    name: "Beatriz Souza Lima",
    initials: "BS",
    course: "Bacharelado em Ciência da Computação",
    campus: "Câmpus Sorocaba",
    pedagogicalProject: "Projeto Pedagógico 2021",
    status: "Formando",
    requiredHours: 210,
    approvedHours: 170,
    pendingHours: 40,
  },
  {
    ra: "801129",
    name: "Thiago Cardoso Dias",
    initials: "TC",
    course: "Bacharelado em Ciência da Computação",
    campus: "Câmpus Sorocaba",
    pedagogicalProject: "Projeto Pedagógico 2021",
    status: "Matrícula Regular",
    requiredHours: 210,
    approvedHours: 110,
    pendingHours: 4,
  },
  {
    ra: "812001",
    name: "Aline Oliveira Costa",
    initials: "AO",
    course: "Bacharelado em Ciência da Computação",
    campus: "Câmpus Sorocaba",
    pedagogicalProject: "Projeto Pedagógico 2021",
    status: "Matrícula Regular",
    requiredHours: 210,
    approvedHours: 140,
    pendingHours: 20,
  },
  {
    ra: "800311",
    name: "Rodrigo Cunha Souza",
    initials: "RC",
    course: "Bacharelado em Ciência da Computação",
    campus: "Câmpus Sorocaba",
    pedagogicalProject: "Projeto Pedagógico 2021",
    status: "Matrícula Regular",
    requiredHours: 210,
    approvedHours: 155,
    pendingHours: 10,
  },
];
